// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2sGU8nOvQGPMvFBqQ4ASqZl_NVzB4xls',
    appId: '1:886258792239:web:678c8ff098beac999213da',
    messagingSenderId: '886258792239',
    projectId: 'fir-chat-app-1b811',
    authDomain: 'fir-chat-app-1b811.firebaseapp.com',
    storageBucket: 'fir-chat-app-1b811.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcRpH1SRgO0mruET17bpXpBCNbwVA_1fg',
    appId: '1:886258792239:android:3dc8202fbb0497bf9213da',
    messagingSenderId: '886258792239',
    projectId: 'fir-chat-app-1b811',
    storageBucket: 'fir-chat-app-1b811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebjwMM0dpkvl4wIBU6i-jQufDOVrNzac',
    appId: '1:886258792239:ios:65445d83f92bbd9d9213da',
    messagingSenderId: '886258792239',
    projectId: 'fir-chat-app-1b811',
    storageBucket: 'fir-chat-app-1b811.appspot.com',
    iosClientId: '886258792239-rl4kaov5qmmdqns18m7srf58udfg4anh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBebjwMM0dpkvl4wIBU6i-jQufDOVrNzac',
    appId: '1:886258792239:ios:ae11a0051d93aa739213da',
    messagingSenderId: '886258792239',
    projectId: 'fir-chat-app-1b811',
    storageBucket: 'fir-chat-app-1b811.appspot.com',
    iosClientId: '886258792239-5psg6ktundcu788l4np1mn822scvv4il.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
